# Generated by Django 3.0.7 on 2020-06-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_patentsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentsummary',
            name='pr6',
            field=models.PositiveIntegerField(),
        ),
    ]
